version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: macrolake-postgres
    environment:
      POSTGRES_USER: test-user
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: macro_datalake
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  minio:
    image: minio/minio
    container_name: macrolake-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: admin123
    command: server /data --console-address ":9001"
    volumes:
      - ./minio-data:/data
    ports:
      - "9000:9000"
      - "9001:9001"


volumes:
  postgres_data:
  minio_data:
  pgadmin_data: